version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"


  web:
    build: .
    container_name: drf_container
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db


  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build: .
    command: celery -A django_cron worker -l info
    user: "nobody"
    environment:
      - CELERY_BROKER_URL=redis://redis_container:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_container:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A django_cron beat -l info
    environment:
      - CELERY_BROKER_URL=redis://redis_container:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_container:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
